server:
  port: 8189
  servlet:
    context-path: /market
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=geekmark
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
jwt:
  secret: urio3748rt87foiweufrwlqgfo34tr7tr874trgfg878453345yrfgshygskjar7striq3g4fkgire